status = [
  "x86 tests (ubuntu-latest)",
  "x86 tests (macos-latest)",
  "x86 tests (windows-latest)",
  "aarch64 tests (ubuntu-latest)",
  "Format",
  "Clippy",
  "ci/gitlab/git.rwth-aachen.de",
]
delete_merged_branches = true
timeout_sec = 7200
